baseURL = "https://misterclarity.com"
disableLanguages = ["Fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "misterclarity"
title = "Mister Clarity | Relationship Renaissance"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [The Brandalicious.](https://www.thebrandalicious.com/) All Rights Reserved"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/ro"
copyright = "Copyright &copy; 2020 [The Brandalicious.](https://www.thebrandalicious.com/) All Rights Reserved"
home = "Acasă"
languageCode = "ro-ro"
languageName = "Ro"
weight = "2"
[[menu.main]]
URL = "feature"
name = "feature"
weight = 2
[[menu.main]]
URL = "services"
name = "service"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "portfolio"
weight = 4
[[menu.main]]
URL = "testimonial"
name = "testimonial"
weight = 5
[[menu.main]]
URL = "pricing"
name = "pricing"
weight = 6
[[menu.main]]
URL = "blog"
name = "blog"
weight = 7
[[menu.main]]
URL = "contact"
name = "contact"
[[menu.static]]
URL = "https://www.spaceholderz.com/"
name = "spaceholderz"
[params]
author = "The Brandalicious"
biglogo = "images/enhancedLogo.png"
description = "Renaissance Guide helping you become spontaneous through (re)connecting with instincts."
google_analytics_id = "UA-173554268-1"
logo = "images/logo.png"
post_share = true
[params.map]
enable = false
gmap_api = ""
map_latitude = "48.126404"
map_longitude = "16.283692"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "https://static.oracle.com/cdn/apex/19.2.0.00.18/libraries/font-apex/2.1/css/font-apex.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/logo.png"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/misterclarity"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/misterclarity"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/mister_clarity"
